name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  full-test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: |
        env -C perftest ./setup.sh
        sudo apt-get -y install eatmydata
    - name: check with latest Ubuntu development version
      run: |
        # skip check on Ubuntu development version with incus, because there are no such available images
        (! which incus) || exit 0
        sudo -u $USER env -C perftest ./create_template_image ubuntu-daily:devel
